import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/GeneralComponents/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white">
        <Navbar />
        <hr className="w-[80%] m-auto" />
        {children}
      </body>
    </html>
  );
}
